/*
 * This file is generated by jOOQ.
 */
package vn.backend.ksv.repository.generator;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import vn.backend.ksv.repository.generator.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HungDev extends SchemaImpl {

    private static final long serialVersionUID = -1363918271;

    /**
     * The reference instance of <code>hung_dev</code>
     */
    public static final HungDev HUNG_DEV = new HungDev();

    /**
     * The table <code>hung_dev.user</code>.
     */
    public final User USER = vn.backend.ksv.repository.generator.tables.User.USER;

    /**
     * No further instances allowed
     */
    private HungDev() {
        super("hung_dev", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
