/*
 * This file is generated by jOOQ.
 */
package vn.backend.ksv.repository.generator;


import javax.annotation.Generated;

import vn.backend.ksv.repository.generator.tables.User;


/**
 * Convenience access to all tables in hung_dev
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>hung_dev.user</code>.
     */
    public static final User USER = vn.backend.ksv.repository.generator.tables.User.USER;
}
